language: csharp
solution: XlsEpplus.sln

#Setup of mono not required as shown in https://docs.travis-ci.com/user/languages/csharp/, testrunner callup with mono should works anyways...
#mono:
#  - latest

addons:
  apt:
    packages:
      - unixodbc
      - unixodbc-dev
      - libmyodbc
      - libmdbodbc1 

#Ubuntu 14.04 = trusty --> take a more modern distro
#dist: trusty

before_install:
  - nuget install NUnit.Runners -Version 3.9.0 -OutputDirectory testrunner

install:
  - nuget restore XlsEpplus.sln

script:
  - msbuild /p:Configuration=TravisCI /p:Platform="Any CPU" /p:PostBuildEvent="" XlsEpplus.sln

after_script:
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./XlsEpplus.Test/bin/TravisCI/CompuMaster.Test.XlsEpplus.dll